language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox