name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  php7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
      - run: |
          composer install --prefer-dist
          vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox