name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  php7-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MilesChou/composer-action/7.1@master
        with:
          args: install --no-interaction --no-suggest 
      - run:
          vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox

  php7-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MilesChou/composer-action/7.2@master
        with:
          args: install --no-interaction --no-suggest 
      - run:
          vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox
          
  php7-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MilesChou/composer-action/7.3@master
        with:
          args: install --no-interaction --no-suggest 
      - run:
          vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox
  php7-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MilesChou/composer-action/7.4@master
        with:
          args: install --no-interaction --no-suggest 
      - run:
          vendor/bin/phpunit --configuration PHPUnit.xml --testsuit pinpoint --testdox
